name: CI

defaults:
  run:
    working-directory: build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: "8.2"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          path: build

      - name: Extract tag name
        id: tag
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set version in composer.json
        run: |
          VERSION=${{ steps.tag.outputs.SOURCE_TAG }}
          VERSION=${VERSION#v}
          jq --arg v "$VERSION" '{version: $v} + .' composer.json > composer.json.tmp
          mv composer.json.tmp composer.json

      - name: Sync composer.lock
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: update
          args: --lock --no-install --no-scripts
          working_dir: build
          php_extensions: pdo_sqlite pdo_mysql

      - name: Build
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          dev: no
          args: --optimize-autoloader
          working_dir: build
          php_extensions: pdo_sqlite pdo_mysql

      - name: Package
        run: |
          sudo rm -rf var/cache/*
          tar -czf strichliste-backend-${{ steps.tag.outputs.SOURCE_TAG }}.tar.gz .env *

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          name: Release ${{ steps.tag.outputs.SOURCE_TAG }}
          tag_name: ${{ steps.tag.outputs.SOURCE_TAG }}
          files: build/strichliste-backend-${{ steps.tag.outputs.SOURCE_TAG }}.tar.gz
